#pragma once

#define COMPUTE_BINDING_LIGHT_BUFFER 0
#define COMPUTE_BINDING_GRID_BUFFER 1
#define COMPUTE_BINDING_LIGHT_INDEX_BUFFER 2
#define COMPUTE_BINDING_ACTIVE_CLUSTERS_BUFFER 3
#define COMPUTE_BINDING_TEST4 4
#define COMPUTE_BINDING_TEST5 5
#define COMPUTE_BINDING_TEST6 6