name: Build & Version

on:
  push:
    branches:
      - main
      - master
      - test  
    paths:
      - '**.h'
      - '**.cpp'
      - '**.sln'
#  pull_request:
#    types:
#      [closed]
#    branches:
#      - main
#      - master
#    paths:
#      - '**.h'
#      - '**.cpp'
#      - '**.sln'
  workflow_dispatch:

concurrency:
  group: "build"
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: windows-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Generate Build Info
        run: python Scripts/generate_build_info.py

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Project
        run: msbuild CSC8503.sln /p:Configuration=Release

      - name: Configure Git User
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: |
            build.h
            build.json

      - name: Create Git Tag
        run: |
          git tag v1.0.${{ github.run_number }}
          git push origin --tags

