name: Build & Version

on:
  push:
    branches:
      - main
      - master
      - test  
    paths:
      - '**.h'
      - '**.cpp'
      - '**.sln'
#  pull_request:
#    types:
#      [closed]
#    branches:
#      - main
#      - master
#    paths:
#      - '**.h'
#      - '**.cpp'
#      - '**.sln'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

concurrency:
  group: "build"
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write

jobs:
  check-new-commits:
    runs-on: ubuntu-latest
    outputs:
      has_new_commits: ${{ steps.check_commits.outputs.has_new_commits }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full history is available

      - name: Check for new commits since last run
        id: check_commits
        run: |
          LAST_RUN=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ github.workflow }}/runs?per_page=2" \
          | jq -r '.workflow_runs[1].created_at')

          if [[ "$LAST_RUN" == "null" ]]; then
            echo "No previous runs found. Running workflow."
            echo "has_new_commits=true" >> $GITHUB_ENV
            exit 0
          fi

          # Get new commits since last run
          NEW_COMMITS=$(git rev-list --count HEAD --since="$LAST_RUN")

          if [[ "$NEW_COMMITS" -gt 0 ]]; then
            echo "New commits found since last run."
            echo "has_new_commits=true" >> $GITHUB_ENV
          else
            echo "No new commits found."
            echo "has_new_commits=false" >> $GITHUB_ENV
          fi
  build:
    needs: check-new-commits
    runs-on: windows-latest
    #if : github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'schedule' 
      && needs.check-new-commits.outputs.has_new_commits == 'true')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Generate Build Info
        run: python Scripts/generate_build_info.py

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Project
        run: msbuild CSC8503.sln /p:Configuration=Release

      - name: Configure Git User
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: |
            build.h
            build.json

      - name: Create Git Tag
        run: |
          git tag v1.0.${{ github.run_number }}
          git push origin --tags

